# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mpui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1219, 792)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#icononlywidget{\n"
"    \n"
"    background-color:#33334f;\n"
"    border:none;\n"
"\n"
"}\n"
"#icononlywidget QPushButton:hover{\n"
"    \n"
"    background-color:#2495f3\n"
"\n"
"\n"
"\n"
"}\n"
"#icononlywidget QPushButton:checked{\n"
"    background-color:#2495f3;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#fullmenuwidget{\n"
"    background-color: #33334f;\n"
"    \n"
"\n"
" }\n"
"#fullmenuwidget QPushButton:hover{\n"
"    background-color:#2495f3;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#fullmenuwidget QPushButton:checked{    \n"
"    background-color:#2495f3;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#threelinebtn{    \n"
"    border:none;    \n"
"}\n"
"#icononlywidget QPushButton,QLabel{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#fullmenuwidget QPushButton{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#new_passwordbtn{\n"
"\n"
"border:none;\n"
"}\n"
"#password_confirmbtn1{\n"
"border:none;\n"
"}\n"
"#widget{\n"
"    background-color: #2296f2;\n"
"}\n"
"#pushButton_15{\n"
"background-color: #1869a9;\n"
"}\n"
"#pushButton_16{\n"
"background-color: #1869a9;\n"
"}\n"
"#widget_5{\n"
"    background-color: #7E9090;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.fullmenuwidget = QtWidgets.QWidget(self.centralwidget)
        self.fullmenuwidget.setObjectName("fullmenuwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fullmenuwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_16 = QtWidgets.QPushButton(self.fullmenuwidget)
        self.pushButton_16.setEnabled(True)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_16.setTabletTracking(False)
        self.pushButton_16.setAutoFillBackground(False)
        self.pushButton_16.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/shield.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_2.addWidget(self.pushButton_16)
        spacerItem = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scanbtn2 = QtWidgets.QPushButton(self.fullmenuwidget)
        self.scanbtn2.setMinimumSize(QtCore.QSize(0, 99))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.scanbtn2.setFont(font)
        self.scanbtn2.setTabletTracking(False)
        self.scanbtn2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scanbtn2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scanbtn2.setAutoFillBackground(False)
        self.scanbtn2.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scanbtn2.setIcon(icon1)
        self.scanbtn2.setIconSize(QtCore.QSize(55, 55))
        self.scanbtn2.setCheckable(True)
        self.scanbtn2.setAutoExclusive(True)
        self.scanbtn2.setObjectName("scanbtn2")
        self.verticalLayout_2.addWidget(self.scanbtn2)
        self.vaultbtn2 = QtWidgets.QPushButton(self.fullmenuwidget)
        self.vaultbtn2.setMinimumSize(QtCore.QSize(0, 99))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.vaultbtn2.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/image (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vaultbtn2.setIcon(icon2)
        self.vaultbtn2.setIconSize(QtCore.QSize(55, 55))
        self.vaultbtn2.setCheckable(True)
        self.vaultbtn2.setAutoExclusive(True)
        self.vaultbtn2.setObjectName("vaultbtn2")
        self.verticalLayout_2.addWidget(self.vaultbtn2)
        self.settingsbtn2 = QtWidgets.QPushButton(self.fullmenuwidget)
        self.settingsbtn2.setMinimumSize(QtCore.QSize(0, 99))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.settingsbtn2.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/image (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsbtn2.setIcon(icon3)
        self.settingsbtn2.setIconSize(QtCore.QSize(55, 55))
        self.settingsbtn2.setCheckable(True)
        self.settingsbtn2.setAutoExclusive(True)
        self.settingsbtn2.setObjectName("settingsbtn2")
        self.verticalLayout_2.addWidget(self.settingsbtn2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 449, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(self.fullmenuwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.gridLayout.addWidget(self.fullmenuwidget, 0, 1, 1, 1)
        self.mainbodywidget = QtWidgets.QWidget(self.centralwidget)
        self.mainbodywidget.setStyleSheet("")
        self.mainbodywidget.setObjectName("mainbodywidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainbodywidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.mainbodywidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.threelinebtn = QtWidgets.QPushButton(self.widget)
        self.threelinebtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.threelinebtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.threelinebtn.setIcon(icon5)
        self.threelinebtn.setIconSize(QtCore.QSize(55, 55))
        self.threelinebtn.setCheckable(True)
        self.threelinebtn.setAutoExclusive(True)
        self.threelinebtn.setObjectName("threelinebtn")
        self.horizontalLayout_2.addWidget(self.threelinebtn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainbodywidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.scanwt = QtWidgets.QWidget()
        self.scanwt.setStyleSheet("")
        self.scanwt.setObjectName("scanwt")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scanwt)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_5 = QtWidgets.QWidget(self.scanwt)
        self.widget_5.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_20.setSpacing(11)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.normal_file_scan_widget = QtWidgets.QWidget()
        self.normal_file_scan_widget.setObjectName("normal_file_scan_widget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.normal_file_scan_widget)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_6 = QtWidgets.QWidget(self.normal_file_scan_widget)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem2)
        self.normal_file_scan_notification = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.normal_file_scan_notification.setFont(font)
        self.normal_file_scan_notification.setStyleSheet("color: rgb(85, 255, 0);")
        self.normal_file_scan_notification.setText("")
        self.normal_file_scan_notification.setObjectName("normal_file_scan_notification")
        self.verticalLayout_25.addWidget(self.normal_file_scan_notification, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.normal_file_scan_select = QtWidgets.QPushButton(self.widget_6)
        self.normal_file_scan_select.setMinimumSize(QtCore.QSize(222, 66))
        self.normal_file_scan_select.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.normal_file_scan_select.setFont(font)
        self.normal_file_scan_select.setStyleSheet("background-color:#0CB754;\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #0CB754")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.normal_file_scan_select.setIcon(icon6)
        self.normal_file_scan_select.setIconSize(QtCore.QSize(44, 44))
        self.normal_file_scan_select.setObjectName("normal_file_scan_select")
        self.verticalLayout_25.addWidget(self.normal_file_scan_select, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem3)
        self.verticalLayout_21.addWidget(self.widget_6)
        self.stackedWidget_2.addWidget(self.normal_file_scan_widget)
        self.advanced_file_scan_widget = QtWidgets.QWidget()
        self.advanced_file_scan_widget.setObjectName("advanced_file_scan_widget")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.advanced_file_scan_widget)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem4)
        self.advanced_scan_notification2 = QtWidgets.QLabel(self.advanced_file_scan_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.advanced_scan_notification2.setFont(font)
        self.advanced_scan_notification2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.advanced_scan_notification2.setStyleSheet("color: rgb(71, 214, 0);")
        self.advanced_scan_notification2.setText("")
        self.advanced_scan_notification2.setObjectName("advanced_scan_notification2")
        self.verticalLayout_24.addWidget(self.advanced_scan_notification2, 0, QtCore.Qt.AlignHCenter)
        self.advanced_scan_selectbtn = QtWidgets.QPushButton(self.advanced_file_scan_widget)
        self.advanced_scan_selectbtn.setMinimumSize(QtCore.QSize(222, 66))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.advanced_scan_selectbtn.setFont(font)
        self.advanced_scan_selectbtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.advanced_scan_selectbtn.setStyleSheet("background-color:#0CB754;\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #0CB754")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advanced_scan_selectbtn.setIcon(icon7)
        self.advanced_scan_selectbtn.setIconSize(QtCore.QSize(44, 44))
        self.advanced_scan_selectbtn.setObjectName("advanced_scan_selectbtn")
        self.verticalLayout_24.addWidget(self.advanced_scan_selectbtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem5)
        self.stackedWidget_2.addWidget(self.advanced_file_scan_widget)
        self.full_scan_widget = QtWidgets.QWidget()
        self.full_scan_widget.setObjectName("full_scan_widget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.full_scan_widget)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame = QtWidgets.QFrame(self.full_scan_widget)
        self.frame.setStyleSheet("#frame QPushButton:hover{\n"
"    background-color:#2495f3;\n"
"    \n"
"    \n"
"    color: rgb(0, 170, 255);\n"
"\n"
"}\n"
"#frame QPushButton:checked{    \n"
"    background-color:#2495f3;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        spacerItem6 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(85, 255, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_23.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.full_scanbtn = QtWidgets.QPushButton(self.frame)
        self.full_scanbtn.setMinimumSize(QtCore.QSize(222, 66))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.full_scanbtn.setFont(font)
        self.full_scanbtn.setStyleSheet("background-color:#0CB754;\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #0CB754")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.full_scanbtn.setIcon(icon8)
        self.full_scanbtn.setIconSize(QtCore.QSize(44, 44))
        self.full_scanbtn.setObjectName("full_scanbtn")
        self.verticalLayout_23.addWidget(self.full_scanbtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(0, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem7)
        self.verticalLayout_22.addWidget(self.frame)
        self.stackedWidget_2.addWidget(self.full_scan_widget)
        self.verticalLayout_20.addWidget(self.stackedWidget_2)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setStyleSheet("#widget_7 QPushButton{\n"
"\n"
"    background-color: #1869a9;\n"
"    padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #0CB754\n"
"}\n"
"\n"
"#widget_7 QPushButton:hover{\n"
"    \n"
"    background-color:rgb(14, 208, 95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#widget_7 QPushButton:checked{    \n"
"    \n"
"    background-color:rgb(12, 183, 84);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.full_scan_btn = QtWidgets.QPushButton(self.widget_7)
        self.full_scan_btn.setMinimumSize(QtCore.QSize(0, 144))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.full_scan_btn.setFont(font)
        self.full_scan_btn.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/malware.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.full_scan_btn.setIcon(icon9)
        self.full_scan_btn.setIconSize(QtCore.QSize(55, 55))
        self.full_scan_btn.setCheckable(True)
        self.full_scan_btn.setAutoExclusive(True)
        self.full_scan_btn.setObjectName("full_scan_btn")
        self.horizontalLayout_10.addWidget(self.full_scan_btn)
        self.advanced_file_scanbtn = QtWidgets.QPushButton(self.widget_7)
        self.advanced_file_scanbtn.setMinimumSize(QtCore.QSize(0, 144))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.advanced_file_scanbtn.setFont(font)
        self.advanced_file_scanbtn.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advanced_file_scanbtn.setIcon(icon10)
        self.advanced_file_scanbtn.setIconSize(QtCore.QSize(55, 55))
        self.advanced_file_scanbtn.setCheckable(True)
        self.advanced_file_scanbtn.setAutoRepeat(False)
        self.advanced_file_scanbtn.setAutoExclusive(True)
        self.advanced_file_scanbtn.setObjectName("advanced_file_scanbtn")
        self.horizontalLayout_10.addWidget(self.advanced_file_scanbtn)
        self.normal_file_scanbtn = QtWidgets.QPushButton(self.widget_7)
        self.normal_file_scanbtn.setMinimumSize(QtCore.QSize(0, 144))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.normal_file_scanbtn.setFont(font)
        self.normal_file_scanbtn.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/scanner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.normal_file_scanbtn.setIcon(icon11)
        self.normal_file_scanbtn.setIconSize(QtCore.QSize(55, 55))
        self.normal_file_scanbtn.setCheckable(True)
        self.normal_file_scanbtn.setAutoExclusive(True)
        self.normal_file_scanbtn.setObjectName("normal_file_scanbtn")
        self.horizontalLayout_10.addWidget(self.normal_file_scanbtn)
        self.verticalLayout_20.addWidget(self.widget_7)
        self.verticalLayout_13.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.scanwt)
        self.valutwt = QtWidgets.QWidget()
        self.valutwt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.valutwt.setObjectName("valutwt")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.valutwt)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.vault_password_notfication = QtWidgets.QWidget(self.valutwt)
        self.vault_password_notfication.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vault_password_notfication.setAutoFillBackground(False)
        self.vault_password_notfication.setObjectName("vault_password_notfication")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.vault_password_notfication)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem8 = QtWidgets.QSpacerItem(20, 350, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.vault_password_linedit = QtWidgets.QLineEdit(self.vault_password_notfication)
        self.vault_password_linedit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 22px;\n"
"type=\"password\"")
        self.vault_password_linedit.setText("")
        self.vault_password_linedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.vault_password_linedit.setObjectName("vault_password_linedit")
        self.horizontalLayout_8.addWidget(self.vault_password_linedit)
        self.vallt_password_confirm = QtWidgets.QPushButton(self.vault_password_notfication)
        self.vallt_password_confirm.setStyleSheet("border:none;\n"
"font: 14pt \"Arial\";\n"
"")
        self.vallt_password_confirm.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vallt_password_confirm.setIcon(icon12)
        self.vallt_password_confirm.setIconSize(QtCore.QSize(31, 31))
        self.vallt_password_confirm.setObjectName("vallt_password_confirm")
        self.horizontalLayout_8.addWidget(self.vallt_password_confirm)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.vault_password_notification = QtWidgets.QLabel(self.vault_password_notfication)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vault_password_notification.setFont(font)
        self.vault_password_notification.setStyleSheet("color: rgb(42, 152, 230);")
        self.vault_password_notification.setAlignment(QtCore.Qt.AlignCenter)
        self.vault_password_notification.setObjectName("vault_password_notification")
        self.verticalLayout_14.addWidget(self.vault_password_notification)
        spacerItem11 = QtWidgets.QSpacerItem(20, 350, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem11)
        self.verticalLayout_11.addWidget(self.vault_password_notfication)
        self.stackedWidget.addWidget(self.valutwt)
        self.updatewt = QtWidgets.QWidget()
        self.updatewt.setObjectName("updatewt")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.updatewt)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.updatewt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgb(120, 133, 150);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.updatewt)
        self.settingswt = QtWidgets.QWidget()
        self.settingswt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.settingswt.setObjectName("settingswt")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.settingswt)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settingswt1 = QtWidgets.QWidget(self.settingswt)
        self.settingswt1.setObjectName("settingswt1")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.settingswt1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_4 = QtWidgets.QWidget(self.settingswt1)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem13)
        self.passwordbtn = QtWidgets.QPushButton(self.widget_4)
        self.passwordbtn.setMinimumSize(QtCore.QSize(301, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.passwordbtn.setFont(font)
        self.passwordbtn.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #2196f3")
        self.passwordbtn.setIconSize(QtCore.QSize(40, 40))
        self.passwordbtn.setCheckable(True)
        self.passwordbtn.setAutoExclusive(True)
        self.passwordbtn.setObjectName("passwordbtn")
        self.verticalLayout_16.addWidget(self.passwordbtn)
        self.change_passwordbtn1 = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_passwordbtn1.sizePolicy().hasHeightForWidth())
        self.change_passwordbtn1.setSizePolicy(sizePolicy)
        self.change_passwordbtn1.setMinimumSize(QtCore.QSize(301, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.change_passwordbtn1.setFont(font)
        self.change_passwordbtn1.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color:#2196f3\n"
"")
        self.change_passwordbtn1.setIconSize(QtCore.QSize(40, 40))
        self.change_passwordbtn1.setObjectName("change_passwordbtn1")
        self.verticalLayout_16.addWidget(self.change_passwordbtn1)
        self.edit_password_notification = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.edit_password_notification.setFont(font)
        self.edit_password_notification.setStyleSheet("color: rgb(42, 152, 230);")
        self.edit_password_notification.setText("")
        self.edit_password_notification.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_password_notification.setObjectName("edit_password_notification")
        self.verticalLayout_16.addWidget(self.edit_password_notification)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem14)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout_17.addWidget(self.widget_4)
        self.verticalLayout_7.addWidget(self.settingswt1)
        self.stackedWidget.addWidget(self.settingswt)
        self.infowt = QtWidgets.QWidget()
        self.infowt.setStyleSheet("background-color:rgb(120, 133, 150);")
        self.infowt.setObjectName("infowt")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.infowt)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.infowt)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.stackedWidget.addWidget(self.infowt)
        self.change_password_page = QtWidgets.QWidget()
        self.change_password_page.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.change_password_page.setObjectName("change_password_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.change_password_page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.change_password_page)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.new_passwordbar = QtWidgets.QLineEdit(self.widget_2)
        self.new_passwordbar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.new_passwordbar.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"border: 2px solid gray;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 22px;\n"
"")
        self.new_passwordbar.setText("")
        self.new_passwordbar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_passwordbar.setObjectName("new_passwordbar")
        self.horizontalLayout_4.addWidget(self.new_passwordbar, 0, QtCore.Qt.AlignLeft)
        self.new_passwordbtn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.new_passwordbtn.setFont(font)
        self.new_passwordbtn.setStyleSheet("")
        self.new_passwordbtn.setObjectName("new_passwordbtn")
        self.horizontalLayout_4.addWidget(self.new_passwordbtn)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.password_confirmbar = QtWidgets.QLineEdit(self.widget_2)
        self.password_confirmbar.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"border: 2px solid gray;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 22px;\n"
"")
        self.password_confirmbar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_confirmbar.setObjectName("password_confirmbar")
        self.horizontalLayout_3.addWidget(self.password_confirmbar, 0, QtCore.Qt.AlignLeft)
        self.password_confirmbtn1 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_confirmbtn1.setFont(font)
        self.password_confirmbtn1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.password_confirmbtn1.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #2196f3")
        self.password_confirmbtn1.setIcon(icon12)
        self.password_confirmbtn1.setIconSize(QtCore.QSize(22, 22))
        self.password_confirmbtn1.setObjectName("password_confirmbtn1")
        self.horizontalLayout_3.addWidget(self.password_confirmbtn1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.password_notificationbtn1 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_notificationbtn1.sizePolicy().hasHeightForWidth())
        self.password_notificationbtn1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.password_notificationbtn1.setFont(font)
        self.password_notificationbtn1.setStyleSheet("color: rgb(42, 152, 230);")
        self.password_notificationbtn1.setText("")
        self.password_notificationbtn1.setAlignment(QtCore.Qt.AlignCenter)
        self.password_notificationbtn1.setObjectName("password_notificationbtn1")
        self.verticalLayout_9.addWidget(self.password_notificationbtn1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem21)
        self.verticalLayout_8.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.change_password_page)
        self.new_password_page = QtWidgets.QWidget()
        self.new_password_page.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.new_password_page.setObjectName("new_password_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.new_password_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem22 = QtWidgets.QSpacerItem(20, 301, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem22)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.previos_password_lineedit = QtWidgets.QLineEdit(self.new_password_page)
        self.previos_password_lineedit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.previos_password_lineedit.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"border: 2px solid gray;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 22px;\n"
"")
        self.previos_password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.previos_password_lineedit.setObjectName("previos_password_lineedit")
        self.horizontalLayout_5.addWidget(self.previos_password_lineedit)
        self.pushButton_2 = QtWidgets.QPushButton(self.new_password_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border:none;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem24)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem25)
        self.newpassword_lineedit = QtWidgets.QLineEdit(self.new_password_page)
        self.newpassword_lineedit.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"border: 2px solid gray;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 22px;\n"
"")
        self.newpassword_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpassword_lineedit.setObjectName("newpassword_lineedit")
        self.horizontalLayout_6.addWidget(self.newpassword_lineedit)
        self.pushButton_3 = QtWidgets.QPushButton(self.new_password_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border:none;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem26)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.confirm_password_lineedit = QtWidgets.QLineEdit(self.new_password_page)
        self.confirm_password_lineedit.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"border: 2px solid gray;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 22px;\n"
"")
        self.confirm_password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password_lineedit.setObjectName("confirm_password_lineedit")
        self.horizontalLayout_7.addWidget(self.confirm_password_lineedit)
        self.edit_password_confimbtn = QtWidgets.QPushButton(self.new_password_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.edit_password_confimbtn.setFont(font)
        self.edit_password_confimbtn.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: #2196f3")
        self.edit_password_confimbtn.setObjectName("edit_password_confimbtn")
        self.horizontalLayout_7.addWidget(self.edit_password_confimbtn)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.edit_password_notification_2 = QtWidgets.QLabel(self.new_password_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.edit_password_notification_2.setFont(font)
        self.edit_password_notification_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.edit_password_notification_2.setStyleSheet("color: rgb(42, 152, 230);")
        self.edit_password_notification_2.setText("")
        self.edit_password_notification_2.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_password_notification_2.setObjectName("edit_password_notification_2")
        self.verticalLayout_10.addWidget(self.edit_password_notification_2)
        spacerItem29 = QtWidgets.QSpacerItem(20, 301, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem29)
        self.stackedWidget.addWidget(self.new_password_page)
        self.vault_look = QtWidgets.QWidget()
        self.vault_look.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.vault_look.setObjectName("vault_look")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.vault_look)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_3 = QtWidgets.QWidget(self.vault_look)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.vault_lock_addfilrbtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vault_lock_addfilrbtn.setFont(font)
        self.vault_lock_addfilrbtn.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"")
        self.vault_lock_addfilrbtn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/listing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vault_lock_addfilrbtn.setIcon(icon13)
        self.vault_lock_addfilrbtn.setIconSize(QtCore.QSize(33, 33))
        self.vault_lock_addfilrbtn.setObjectName("vault_lock_addfilrbtn")
        self.verticalLayout_18.addWidget(self.vault_lock_addfilrbtn, 0, QtCore.Qt.AlignLeft)
        self.vault_lock_retrivefilebtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vault_lock_retrivefilebtn.setFont(font)
        self.vault_lock_retrivefilebtn.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"color: rgb(0, 0, 0);\n"
"border-style: outset;\n"
"padding: 2px ;\n"
"border-width: 6px ;\n"
"border-radius: 10px ;\n"
"border-color: rgb(49, 58, 70);\n"
"")
        self.vault_lock_retrivefilebtn.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/message.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vault_lock_retrivefilebtn.setIcon(icon14)
        self.vault_lock_retrivefilebtn.setIconSize(QtCore.QSize(33, 33))
        self.vault_lock_retrivefilebtn.setObjectName("vault_lock_retrivefilebtn")
        self.verticalLayout_18.addWidget(self.vault_lock_retrivefilebtn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.listWidget = QtWidgets.QListWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"color: rgb(42, 152, 230);")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_19.addWidget(self.listWidget)
        self.verticalLayout_12.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.vault_look)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.mainbodywidget, 0, 2, 1, 1)
        self.icononlywidget = QtWidgets.QWidget(self.centralwidget)
        self.icononlywidget.setStyleSheet("")
        self.icononlywidget.setObjectName("icononlywidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icononlywidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_15 = QtWidgets.QPushButton(self.icononlywidget)
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setIconSize(QtCore.QSize(57, 55))
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout.addWidget(self.pushButton_15)
        spacerItem30 = QtWidgets.QSpacerItem(20, 453, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem30)
        self.scanbtn1 = QtWidgets.QPushButton(self.icononlywidget)
        self.scanbtn1.setMinimumSize(QtCore.QSize(0, 99))
        self.scanbtn1.setStyleSheet("")
        self.scanbtn1.setText("")
        self.scanbtn1.setIcon(icon1)
        self.scanbtn1.setIconSize(QtCore.QSize(55, 55))
        self.scanbtn1.setCheckable(True)
        self.scanbtn1.setAutoExclusive(True)
        self.scanbtn1.setObjectName("scanbtn1")
        self.verticalLayout.addWidget(self.scanbtn1)
        self.vaultbtn1 = QtWidgets.QPushButton(self.icononlywidget)
        self.vaultbtn1.setMinimumSize(QtCore.QSize(0, 99))
        self.vaultbtn1.setText("")
        self.vaultbtn1.setIcon(icon2)
        self.vaultbtn1.setIconSize(QtCore.QSize(55, 55))
        self.vaultbtn1.setCheckable(True)
        self.vaultbtn1.setAutoExclusive(True)
        self.vaultbtn1.setObjectName("vaultbtn1")
        self.verticalLayout.addWidget(self.vaultbtn1)
        self.settingsbtn1 = QtWidgets.QPushButton(self.icononlywidget)
        self.settingsbtn1.setMinimumSize(QtCore.QSize(0, 99))
        self.settingsbtn1.setText("")
        self.settingsbtn1.setIcon(icon3)
        self.settingsbtn1.setIconSize(QtCore.QSize(55, 55))
        self.settingsbtn1.setCheckable(True)
        self.settingsbtn1.setAutoExclusive(True)
        self.settingsbtn1.setObjectName("settingsbtn1")
        self.verticalLayout.addWidget(self.settingsbtn1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem31 = QtWidgets.QSpacerItem(20, 404, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem31)
        self.pushButton_14 = QtWidgets.QPushButton(self.icononlywidget)
        self.pushButton_14.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon15)
        self.pushButton_14.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_3.addWidget(self.pushButton_14)
        self.gridLayout.addWidget(self.icononlywidget, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.threelinebtn.toggled['bool'].connect(self.icononlywidget.setVisible) # type: ignore
        self.threelinebtn.toggled['bool'].connect(self.fullmenuwidget.setHidden) # type: ignore
        self.scanbtn1.toggled['bool'].connect(self.scanbtn2.setChecked) # type: ignore
        self.vaultbtn1.toggled['bool'].connect(self.vaultbtn2.setChecked) # type: ignore
        self.settingsbtn1.toggled['bool'].connect(self.settingsbtn2.setChecked) # type: ignore
        self.settingsbtn2.toggled['bool'].connect(self.settingsbtn1.setChecked) # type: ignore
        self.vaultbtn2.toggled['bool'].connect(self.vaultbtn1.setChecked) # type: ignore
        self.scanbtn2.toggled['bool'].connect(self.scanbtn1.setChecked) # type: ignore
        self.pushButton_14.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_5.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scanbtn2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.scanbtn2.setText(_translate("MainWindow", "  Scan                         "))
        self.vaultbtn2.setText(_translate("MainWindow", "  Vault                         "))
        self.settingsbtn2.setText(_translate("MainWindow", "  Settings                    "))
        self.pushButton_5.setText(_translate("MainWindow", "  Exit"))
        self.normal_file_scan_select.setText(_translate("MainWindow", "SELECT FILE"))
        self.advanced_scan_selectbtn.setText(_translate("MainWindow", "  TARGETED SCAN"))
        self.full_scanbtn.setText(_translate("MainWindow", "RUN SMART SCAN"))
        self.full_scan_btn.setText(_translate("MainWindow", "Full scan"))
        self.advanced_file_scanbtn.setText(_translate("MainWindow", "  Directory Scan"))
        self.normal_file_scanbtn.setText(_translate("MainWindow", "Quick Scan"))
        self.vault_password_notification.setText(_translate("MainWindow", "Enter the password"))
        self.label_2.setText(_translate("MainWindow", "No Update"))
        self.passwordbtn.setText(_translate("MainWindow", "Set Password"))
        self.change_passwordbtn1.setText(_translate("MainWindow", "Change password"))
        self.label.setText(_translate("MainWindow", "info"))
        self.new_passwordbtn.setText(_translate("MainWindow", "  New Password"))
        self.password_confirmbtn1.setText(_translate("MainWindow", "  Confirm  "))
        self.pushButton_2.setText(_translate("MainWindow", "Previous Password"))
        self.pushButton_3.setText(_translate("MainWindow", "  New password     "))
        self.edit_password_confimbtn.setText(_translate("MainWindow", "Confim Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
